const test = require('node:test')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { buildApp, launchApp } = require('../zernio/support/electron-app.cjs')

test('Advanced models and export speed support keyboard selection, review and submission in Electron', { timeout: 90000 }, async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bridgeclip-models-e2e-'))
  const appDir = buildApp(path.join(root, 'app'))
  const session = await launchApp({ appDir, userDataDir: path.join(root, 'user-data') })
  t.after(async () => { await session.close(); fs.rmSync(root, { recursive: true, force: true }) })
  const { app, page } = session
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  // Keep the real models:list IPC and parser; replace only the public HTTP catalog.
  // No keys, audio, video or paid inference requests are used in this test.
  await app.evaluate(({ ipcMain }, root) => {
    globalThis.modelTest = { fail: true, calls: [], submitted: null }
    globalThis.fetch = async (url, options) => {
      globalThis.modelTest.calls.push({ url, headers: options.headers })
      if (globalThis.modelTest.fail) throw new Error('Offline catalog')
      if (!url.startsWith('https://openrouter.ai/api/v1/models?')) throw new Error('Unexpected network request')
      const stt = url.endsWith('transcription')
      return Response.json({ data: stt ? [
        { id: 'openai/whisper-large-v3', name: 'OpenAI: Whisper Large V3', architecture: { input_modalities: ['audio'], output_modalities: ['transcription'] } },
        { id: 'openai/gpt-4o-transcribe', name: 'OpenAI: GPT-4o Transcribe', architecture: { input_modalities: ['audio'], output_modalities: ['transcription'] } }
      ] : [
        { id: 'google/gemini-3.8-flash', name: 'Google: Gemini 3.8 Flash', architecture: { input_modalities: ['text', 'image'], output_modalities: ['text'] },
          supported_parameters: ['structured_outputs'], context_length: 1048576, top_provider: { max_completion_tokens: 65536 }, pricing: { prompt: '0.00000075', completion: '0.00000375' } }
      ] })
    }
    ipcMain.removeHandler('settings:load')
    ipcMain.handle('settings:load', () => ({ openrouterConfigured: true, zernioConfigured: false, outputDirectory: root, pythonPath: '', customVocabulary: '' }))
    ipcMain.removeHandler('system:checkTools')
    ipcMain.handle('system:checkTools', () => ({ python: true, pythonDeps: true, ffmpeg: true, ffmpegCaptions: true, ffprobe: true, ytdlp: true, engine: true, bridgeRunner: true }))
    ipcMain.removeHandler('job:start')
    ipcMain.handle('job:start', (_event, config) => { globalThis.modelTest.submitted = config; return { jobId: 'test-advanced', queued: false } })
  }, root)
  await page.reload()
  await page.getByPlaceholder(/or direct link/).fill('https://example.com/video.mp4')
  await page.getByRole('button', { name: 'Use link', exact: true }).click()
  await page.getByRole('radio', { name: 'Automatic', exact: true }).click()
  const steps = page.getByRole('navigation', { name: 'Create steps' })
  await steps.getByRole('button', { name: /Format/ }).click()
  const speeds = page.getByRole('radiogroup', { name: 'Video speed' })
  await speeds.getByRole('radio', { name: '1× (Normal)', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowRight')
  assert.equal(await speeds.getByRole('radio', { name: '1.5×', exact: true }).getAttribute('aria-checked'), 'true')
  const artifacts = process.env.BRIDGECLIP_E2E_SHOTS
  if (artifacts) {
    fs.mkdirSync(artifacts, { recursive: true })
    await page.screenshot({ path: path.join(artifacts, 'advanced-video-speed.png') })
  }
  await steps.getByRole('button', { name: /Clips/ }).click()
  await page.getByText(/60 seconds becomes about 40 seconds/).waitFor()
  await page.getByRole('radio', { name: /Advanced/ }).click()
  await page.getByRole('alert').filter({ hasText: 'Could not load OpenRouter models' }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Generate now', exact: true }).isDisabled(), true)
  await app.evaluate(() => { globalThis.modelTest.fail = false })
  await page.getByRole('button', { name: 'Refresh models' }).click()
  const speech = page.getByRole('combobox', { name: 'Transcription model', exact: true })
  await speech.fill('does not exist')
  await page.getByText('No matching models.', { exact: false }).waitFor()
  await speech.fill('gpt-4o')
  assert.equal(await page.getByRole('option').getAttribute('aria-disabled'), 'true')
  await speech.fill('whisper large')
  await speech.press('ArrowDown')
  await speech.press('Enter')
  assert.equal(await speech.inputValue(), 'OpenAI: Whisper Large V3')
  const planner = page.getByRole('combobox', { name: 'Clip planning model', exact: true })
  await planner.fill('gemini')
  await page.getByRole('option', { name: /Google: Gemini/ }).click()
  assert.equal(await app.evaluate(() => globalThis.modelTest.submitted), null, 'Enter must select a model, not submit a job')
  await page.getByRole('radio', { name: /Economy/ }).click()
  assert.equal(await page.getByRole('combobox').count(), 0)
  await page.getByRole('radio', { name: /Advanced/ }).click()
  assert.equal(await speech.inputValue(), 'OpenAI: Whisper Large V3')
  assert.equal(await planner.inputValue(), 'Google: Gemini 3.8 Flash')
  await app.evaluate(() => { globalThis.modelTest.fail = true })
  await page.getByRole('button', { name: 'Refresh models' }).click()
  await page.getByRole('alert').filter({ hasText: 'Could not load OpenRouter models' }).waitFor()
  assert.equal(await planner.inputValue(), 'Google: Gemini 3.8 Flash')
  await app.evaluate(() => { globalThis.modelTest.fail = false })
  await page.getByRole('button', { name: 'Refresh models' }).click()
  await page.getByRole('alert').filter({ hasText: 'Could not load OpenRouter models' }).waitFor({ state: 'hidden' })
  if (artifacts) await page.screenshot({ path: path.join(artifacts, 'advanced-mode.png') })
  await steps.getByRole('button', { name: /Review/ }).click()
  await page.getByText('1.5× · All exported clips', { exact: true }).waitFor()
  await page.getByText('Advanced · custom models', { exact: true }).waitFor()
  await page.getByText('google/gemini-3.8-flash', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'Generate clips', exact: true }).click()
  await page.getByRole('button', { name: 'View job' }).waitFor()
  const result = await app.evaluate(() => globalThis.modelTest)
  assert.equal(result.submitted.clippingMode, 'advanced')
  assert.equal(result.submitted.plannerModel, 'google/gemini-3.8-flash')
  assert.equal(result.submitted.transcriptionModel, 'openai/whisper-large-v3')
  assert.equal(result.submitted.videoSpeed, 1.5)
  await page.getByRole('button', { name: 'Clip another video' }).click()
  await page.getByPlaceholder(/or direct link/).fill('https://example.com/next.mp4')
  await page.getByRole('button', { name: 'Use link', exact: true }).click()
  await page.getByRole('radio', { name: 'Automatic', exact: true }).click()
  await steps.getByRole('button', { name: /Format/ }).click()
  assert.equal(await speeds.getByRole('radio', { name: '1.5×', exact: true }).getAttribute('aria-checked'), 'true')
  assert.ok(result.calls.every(({ headers }) => !Object.keys(headers).some((name) => name.toLowerCase() === 'authorization')))
  assert.deepEqual(errors, [])
})
